### ISSUE TITLE
Have you ever tried to use hardware decoding?

### ISSUE THREAD

**Issue by KAL-AL** [surfzoid/QtVsPlayer#20]
I am also using PlayM4 library
But I tried to use PlayM4_SetDecodeEngineEx()  Perform hardware decoding 
Can't succeed
mean PlayM4_SetDecodeEngineEx(port,0)  is ok  PlayM4_SetDecodeEngineEx(port,0)  can,t succeed
If you have used hardware decoding  Please tell me the solution
Thank you very much.

**Comment by surfzoid** [comment]
Hi,
no success too, sound like version question of lib and not the good header file.
PlayM4_SetDecodeEngine is in the header, not in the lib or with another signature.

Did you ever use PlayM4_SetStreamOpenMode(g_nPort,STREAME_REALTIME) to play live view without the netSDK.
 I made several test here : https://github.com/surfzoid/HikRtsp

**Comment by surfzoid** [comment]
if you work on other video player, it should be powerful to expand QtVsPlayer.
