### ISSUE TITLE
[Error] Can't launch QtVsPlater on ARM64 - Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by samuel-ongzx** [surfzoid/QtVsPlayer#22]
Thanks for the great work on developing QtVsPlayer for Hikvision!
I ran into some issue trying to run the compiled executable, hope you can help me out. 

My system is on NVIDIA AGX Orin 32GB (ARM64 architecture)
I have compiled QT 5.15.2 from source and used it to compile QtVsPlater without any error. 
After compiling and running `$ QtVsPlayer`, I have the error below:

```
hpr tls index{3}
PlayCtrl || Load libva.so.2 
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

[1]    160602 abort (core dumped)  QtVsPlayer
```

**Comment by surfzoid** [comment]
Hi, Thanks for th feedback.
This is a common error.
Do you run a RPM or DEB system? I have ppa whose include QT.

If you have NVIDIA driver , you try other video plugin platform like eglfs.

This could help : 
export SDL_FRAMEBUFFER_ACCELERATION=false
export QT_QPA_PLATFORMTHEME=gtk2
export QT_LOGGING_RULES="*.debug=false"

export VDPAU_DRIVER=nvidia

You have to setup qt path on your system :  "xcb" in ""

Ensure you have the lib : sudo find /|grep -i qxcb.so

https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/15

**Comment by surfzoid** [comment]
https://github.com/NVlabs/instant-ngp/discussions/300
